package org.example.Exceptions;

import static org.example.Exceptions.MainThrow.*;

public class TryCatchFinally {
        public static void smth1() {smth2();}
        public static void smth2() {smth3();}
        public static void smth3(){};

}
